config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles #Give me the paths of CRUD operations for article
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  #title not null, Ensure there is a title and add minimum and maximum constarints
  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 5000 }
  validates :user_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :articles, dependent: :destroy

  before_save { self.email = email.downcase }

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in? #make theese methods available in our viwes

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user #convert anything to boolean !!
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform this action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController

  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def create
    # render plain: params[:article].inspect #Show what passed through the form
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save # if it passed our validation and saved do the following
      flash[:success] = 'Article was successfully created' # need an explanations
      redirect_to article_path(@article)
    else
      render 'new'
    end
    # @article.save --> save the article into the database
    # redirect_to article_path(@article) --> redirect to another page
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was successfully updated'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was successfully deleted'
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your articles"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show

  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:danger] = "Wrong email or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Alpha-blog, #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Information updated successfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user deleted successfully"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit or update your profile"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only admin user can perform this action"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded-cricle")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="col-md-12 col-md-offset-2">
    <div class="center jumbotron" style="height: 200px; text-align: left; overflow: scroll;">
      <div class="article-title" style="margin-top: -50px; font-weight: bolder; font-size: large">
        <%= link_to article.title, article_path(article) %>
      </div>
      <hr>
      <div class="article-body" style="font-weight: bold;">

        <small style="font-weight: bold">
          Created by: <%= article.user.username if article.user %>
          <br>
          <%= time_ago_in_words(article.created_at) %> ago
        </small>
        <br>
        <hr>
        <%= truncate(article.description, length: 200) %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<!-- if there is any errors while creating the article it will appear here -->
<% if @article.errors.any? %>
  <div class="col-xs-12">
    <div class="card text-white bg-danger mb-3">
      <div class="card-header" style="font-weight: bolder">Error while creating the article</div>
      <div class="card-body">
        <h5 class="card-title" style="font-weight: bolder">The following error has appeared:</h5>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li style="font-weight: bolder"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<!-- our creating article form but with rails helpers -->

<div class="col-xs-12">
  <%= form_for @article do |f| %>
    <div class="form-group">
      <%= f.label :title, style: "font-weight: bolder; font-size: large;" %>
      <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
    </div>
    <div class="form-group">
      <%= f.label :description, style: "font-weight: bolder; font-size: large;" %>
      <%= f.text_area :description, rows: 15, class: "form-control", placeholder: "The article", autofocus: true %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to "Back to Articles", articles_path %>
</div>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center" style="font-weight: bolder">All articles </h1>
<hr>
<div style="width: fit-content;margin: auto;">
  <%= will_paginate @article %>
</div>
<%= render 'article', obj: @articles %>
<div style="width: fit-content;margin: auto;">
  <%= will_paginate @article %>
</div>

app/views/articles/new.html.erb
<h1 style="text-align: center; font-weight: bolder">Create an article</h1>
<div class="container">
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<h2 align="center" style="font-weight: bolder"><%= @article.title %></h2>
<div class="col-md-12 col-md-offset-2">
  <hr>
  <div class="center jumbotron" style="overflow: scroll;">
    <p align="left" style="font-weight: bolder">
      Created by: <%= link_to @article.user.username, user_path(@article.user) if @article.user %>
      <br><small><%= time_ago_in_words(@article.created_at) %> ago</small>
    </p>
    <hr>
    <p align="left" style="font-weight: bold"><%= @article.description %></p>
  </div>
  <%= link_to "View all Articles", articles_path, class: "btn btn-primary" %>
  <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
    <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-success" %>
    <%= link_to "Delete this article", article_path(@article), method: :delete,
                data: { confirm: "Are you sure?" },
                class: "btn btn-danger" %>
  <% end %>
</div>

app/views/categories/index.html.erb
<style>
    .category-data {
        font-weight: bolder;
        height: auto;
        width: fit-content;
        margin: auto;
        border-radius: 7px;
        background-color: #CCCCCC;
    }
</style>
<h1 align="center" style="font-weight: bolder">All categories</h1>
<div style="width: fit-content;margin: auto;" aliign="center"><%= will_paginate %></div>
<hr>
<% @categories.each do |category| %>
  <ul style="list-style: none">
    <div class="center category-data">
      <li>
        <%= link_to "#{category.name}", category_path(category) %>
      </li>
    </div>
  </ul>
<% end %>
<div style="width: fit-content;margin: auto;" align="center"><%= will_paginate %></div>

app/views/categories/new.html.erb
<h1 align="center" style="font-weight: bolder">Create new category</h1>
<!-- if there is any errors while creating the article it will appear here -->
<% if @category.errors.any? %>
  <div class="col-xs-12">
    <div class="card text-white bg-danger mb-3">
      <div class="card-header" style="font-weight: bolder">Error while performing the action</div>
      <div class="card-body">
        <h5 class="card-title" style="font-weight: bolder">The following error has appeared:</h5>
        <ul>
          <% @category.errors.full_messages.each do |msg| %>
            <li style="font-weight: bolder"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<!-- our creating article form but with rails helpers -->

<div class="col-xs-12">
  <%= form_for @category do |f| %>
    <div class="form-group">
      <%= f.label :name, style: "font-weight: bolder; font-size: large;" %>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter name", autofocus: true %>
    </div>

    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to "Back to Articles", articles_path %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="https://github.com/ashawareb">AbdUlRahman Shawareb</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="col-xs-12" style="margin-top: 10px; width: 98%; margin-left: 1%">
  <% flash.each do |name, msg| %>
    <div class='alert alert-<%= "#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #730E15;">
  <%= link_to "Alpha-blog", root_path, class: "navbar-brand", style: "font-size: x-large; font-weight: bolder;" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if logged_in? %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link", style: "color:#FFF; font-weight: bold;" %>
        </li>

        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link", style: "color:#FFF; font-weight: bold;" %>
        </li>

        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user), class: "nav-link", style: "color:#FFF; font-weight: bold;" %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" style="color: #FFFFFF; font-weight: bold" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
          </div>
        </li>
      </ul>

      <ul class="navbar-nav" style="float: right">
        <li class="nav-item">
          <%= link_to "Log out", logout_path, method: :delete, class: "nav-link", style: "color:#FFF; font-weight: bold;" %>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link", style: "color:#FFF; font-weight: bold;" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link", style: "color:#FFF; font-weight: bold;" %>
        </li>
      </ul>
      <ul class="navbar-nav" style="float: right">
        <li class="nav-item">
          <%= link_to "Log in", login_path, class: "nav-link", style: "color:#FFF; font-weight: bold;" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link", style: "color:#FFF; font-weight: bold;" %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>
<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/home.html.erb
<div class=" center jumbotron">
  <h1 class="msg">Welcome to Alpha-blog</h1>
  <%= link_to "Sign up", signup_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/users/_form.html.erb
<!-- if there is any errors while creating the article it will appear here -->
<% if @user.errors.any? %>
  <div class="col-xs-12">
    <div class="card text-white bg-danger mb-3">
      <div class="card-header" style="font-weight: bolder">Error while creating the article</div>
      <div class="card-body">
        <h5 class="card-title" style="font-weight: bolder">The following error has appeared:</h5>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li style="font-weight: bolder"><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

<!-- our creating article form but with rails helpers -->

<div class="col-xs-12">
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :Username, style: "font-weight: bolder; font-size: large;" %>
      <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
    </div>

    <div class="form-group">
      <%= f.label :Email, style: "font-weight: bolder; font-size: large;" %>
      <%= f.email_field :email, class: "form-control", placeholder: "Enter email", autofocus: true %>
    </div>

    <div class="form-group">
      <%= f.label :Password, style: "font-weight: bolder; font-size: large;" %>
      <%= f.password_field :password, class: "form-control", placeholder: "Enter password", autofocus: true %>
    </div>

    <div class="form-group">
      <%= f.submit(@user.new_record? ? "Sign up" : "Update information",
                   class: "btn btn-primary") %>
    </div>
  <% end %>
  <%= link_to "Back to Articles", articles_path %>
</div>

app/views/users/edit.html.erb
<h1 align="center" style="font-weight: bolder">
  Edit <%= @user.username %>'s information
</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<style>
    .user-data {
        font-weight: bolder;
        height: fit-content;
        width: 75%;
        margin: auto;
    }
</style>
<h1 align="center" style="font-weight: bolder">
  All Alpha-bloggers
</h1>
<br>
<hr>
<div style="width: fit-content;margin: auto;">
  <%= will_paginate @users %>
</div>
<% @users.each do |user| %>
  <ul style="list-style: none">
    <div class="center jumbotron user-data">
      <li align="left"><%= link_to gravatar_for(user), user_path(user) %></li>
      <li align="left"><%= link_to user.username, user_path(user) %></li>
      <li align="left"><small><%= pluralize(user.articles.count, "articles") %></small></li>
    </div>
  </ul>
  <hr>
<% end %>
<br>
<div style="width: fit-content;margin: auto;">
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<!-- if there is any errors while creating the article it will appear here -->
<h1 align="center" style="font-weight: bolder">Sign up for Alpha-blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center" style="font-weight: bolder">
  Welcome <%= @user.username %>'s page
</h1>
<br>
<div align="center">
  <%= gravatar_for @user %>
</div>
<br>
<hr>
<h4 align="center" style="font-weight: bolder">
  <%= @user.username %>'s articles
</h4>
<%= render 'articles/article', obj: @user.articles %>
<% if logged_in? && current_user == @user %>
  <%= link_to "Edit profile", edit_user_path(@user), class: "btn btn-primary" %>
<% end %>
<% if logged_in? && current_user.admin? %>
  <%= link_to "Delete user", user_path(@user), method: :delete,
              data: { confirm: "Are you sure you want to delete this user?" },
              class: "btn btn-danger" %>
<% end %>